# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8

# rvm:
# - 2.2.2

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install xcpretty
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/JQSwiftIcon.xcworkspace -scheme JQSwiftIcon-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=YES -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' | xcpretty
- pod lib lint
